name: Vercel Production Deployment

on:
  push:
    branches:
      - main

concurrency:
  group: vercel-production-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build planner WASM (Docker)
        run: npm run build:planner

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel environment (production)
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Run tests (blocking)
        run: npm run test

      - name: Build project artifacts (prebuilt, prod)
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy prebuilt artifacts to Vercel (production)
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}


